#Numpy Arrays

In [ ]:
import numpy as np


In [ ]:
mylist =[1,2,3]
type(mylist)

list

In [ ]:
myarr=np.array(mylist)
myarr

array([1, 2, 3])

In [ ]:
type(myarr)

numpy.ndarray

In [ ]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
len(np.linspace(0,10,21))

21

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,2)

array([[0.55371085, 0.10161896],
       [0.07606988, 0.44998493],
       [0.59421174, 0.30667433],
       [0.59954824, 0.75008608],
       [0.20903019, 0.24565588]])

In [ ]:
np.random.randn(10)

array([ 0.81500416, -2.07479047, -0.11919774,  1.09032256,  0.41054385,
       -0.82373517,  0.70291471,  1.27875935,  0.24758458,  0.54207503])

In [ ]:
np.random.randint(0,7,(3,10))

array([[0, 6, 0, 5, 2, 3, 1, 6, 1, 6],
       [4, 2, 4, 1, 1, 5, 5, 0, 2, 6],
       [6, 0, 1, 1, 6, 4, 6, 2, 3, 0]])

In [ ]:
np.random.seed(42)

In [ ]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr =np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
rand_arr =np.random.randint(0,101,10)
rand_arr


array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [ ]:
rand_arr.max(),rand_arr.min()



(87, 1)

In [ ]:
rand_arr.argmin(),rand_arr.argmax()

(0, 1)

In [ ]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])